workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      groups: [env_files]
      vars:
        MEALDB_API_KEY: $MEALDB_API_KEY
        GEMINI_API_KEY: $GEMINI_API_KEY
        GOOGLE_VISION_API_KEY: $GOOGLE_VISION_API_KEY
        NUTRITIONIX_APP_KEY: $NUTRITIONIX_APP_KEY
        NUTRITIONIX_APP_ID: $NUTRITIONIX_APP_ID
        RAPID_API_KEY: $RAPID_API_KEY
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create .env file
        script: |
          #!/usr/bin/env sh
          set -e
          cat > .env <<'ENVEOF'
          MEALDB_API_KEY=$MEALDB_API_KEY
          GEMINI_API_KEY=$GEMINI_API_KEY
          GOOGLE_VISION_API_KEY=$GOOGLE_VISION_API_KEY
          NUTRITIONIX_APP_KEY=$NUTRITIONIX_APP_KEY
          NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID
          RAPID_API_KEY=$RAPID_API_KEY
          ENVEOF
      - name: Get Flutter dependencies
        script: flutter packages get
      - name: Build iOS
        script: flutter build ios --debug --simulator
    artifacts:
      - build/ios/**/*.app
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
