workflows:
  ios-workflow:
    name: iOS Debug Simulator
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - env_files
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e
          echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/android/app/google-services.json
          echo $IOS_FIREBASE_SECRET > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Get Flutter dependencies
        script: flutter packages get

      - name: Build iOS Debug for Simulator
        script: |
          flutter build ios --debug --simulator \
            --dart-define=MEALDB_API_KEY=$MEALDB_API_KEY \
            --dart-define=GEMINI_API_KEY=$GEMINI_API_KEY \
            --dart-define=GOOGLE_VISION_API_KEY=$GOOGLE_VISION_API_KEY \
            --dart-define=NUTRITIONIX_APP_KEY=$NUTRITIONIX_APP_KEY \
            --dart-define=NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID \
            --dart-define=RAPID_API_KEY=$RAPID_API_KEY

    artifacts:
      - build/ios/**/*.app
      - flutter_drive.log

  android-workflow:
    name: Android Debug APK
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      groups:
        - env_files
      flutter: stable
      java: 17
    scripts:
      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e
          echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/android/app/google-services.json
          echo $IOS_FIREBASE_SECRET > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Get Flutter dependencies
        script: flutter packages get

      - name: Build Android Debug APK
        script: |
          flutter build apk --debug \
            --dart-define=MEALDB_API_KEY=$MEALDB_API_KEY \
            --dart-define=GEMINI_API_KEY=$GEMINI_API_KEY \
            --dart-define=GOOGLE_VISION_API_KEY=$GOOGLE_VISION_API_KEY \
            --dart-define=NUTRITIONIX_APP_KEY=$NUTRITIONIX_APP_KEY \
            --dart-define=NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID \
            --dart-define=RAPID_API_KEY=$RAPID_API_KEY

    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log

  dual-platform-workflow:
    name: iOS + Android Debug Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - env_files
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 17
    scripts:
      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e
          echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/android/app/google-services.json
          echo $IOS_FIREBASE_SECRET > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Get Flutter dependencies
        script: flutter packages get

      - name: Build iOS Debug for Simulator
        script: |
          flutter build ios --debug --simulator \
            --dart-define=MEALDB_API_KEY=$MEALDB_API_KEY \
            --dart-define=GEMINI_API_KEY=$GEMINI_API_KEY \
            --dart-define=GOOGLE_VISION_API_KEY=$GOOGLE_VISION_API_KEY \
            --dart-define=NUTRITIONIX_APP_KEY=$NUTRITIONIX_APP_KEY \
            --dart-define=NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID \
            --dart-define=RAPID_API_KEY=$RAPID_API_KEY

      - name: Build Android Debug APK
        script: |
          flutter build apk --debug \
            --dart-define=MEALDB_API_KEY=$MEALDB_API_KEY \
            --dart-define=GEMINI_API_KEY=$GEMINI_API_KEY \
            --dart-define=GOOGLE_VISION_API_KEY=$GOOGLE_VISION_API_KEY \
            --dart-define=NUTRITIONIX_APP_KEY=$NUTRITIONIX_APP_KEY \
            --dart-define=NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID \
            --dart-define=RAPID_API_KEY=$RAPID_API_KEY

    artifacts:
      - build/ios/**/*.app
      - build/**/outputs/**/*.apk
      - flutter_drive.log
