workflows:
  ios-unsigned-ipa:
    name: iOS Unsigned IPA (Device) + Android Debug
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      groups:
        - env_files
      flutter: stable
      xcode: latest
      cocoapods: default
      java: 17

    scripts:
      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e
          echo "$ANDROID_FIREBASE_SECRET" > "$CM_BUILD_DIR/android/app/google-services.json"
          echo "$IOS_FIREBASE_SECRET" > "$CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist"

      - name: Get Flutter dependencies
        script: |
          set -e
          flutter pub get

      - name: Force iOS deployment target to 14.0
        script: |
          set -e

          # Ensure Podfile has platform :ios, '14.0'
          if grep -q "^platform :ios" ios/Podfile; then
            sed -i '' "s/^platform :ios.*/platform :ios, '14.0'/" ios/Podfile
          else
            echo "platform :ios, '14.0'" | cat - ios/Podfile > ios/Podfile.tmp
            mv ios/Podfile.tmp ios/Podfile
          fi

          # Ensure Xcode project deployment target is 14.0 everywhere
          sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g" ios/Runner.xcodeproj/project.pbxproj

      - name: Install CocoaPods (clean)
        script: |
          set -e
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS unsigned .ipa (device) via xcodebuild archive
        script: |
          set -e

          # Avoid Flutter device build/signing checks
          flutter precache --ios
          flutter pub get

          cd ios
          rm -rf build
          mkdir -p build

          # Archive for device WITHOUT signing
          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/Runner.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGN_IDENTITY="" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            PROVISIONING_PROFILE="" \
            COMPILER_INDEX_STORE_ENABLE=NO

          # Extract the .app from the archive
          APP_PATH="build/Runner.xcarchive/Products/Applications/Runner.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Runner.app not found at $APP_PATH"
            echo "Searching for any .app inside archive..."
            find build/Runner.xcarchive -maxdepth 8 -type d -name "*.app" -print
            exit 1
          fi

          # Package into an unsigned IPA: Payload/Runner.app
          rm -rf build/Payload
          mkdir -p build/Payload
          cp -R "$APP_PATH" build/Payload/

          cd build
          /usr/bin/zip -r -y "Runner-unsigned.ipa" Payload
          cd ../..

      - name: Build Android Debug APK
        script: |
          set -e
          flutter build apk --debug \
            --dart-define=MEALDB_API_KEY=$MEALDB_API_KEY \
            --dart-define=GEMINI_API_KEY=$GEMINI_API_KEY \
            --dart-define=GOOGLE_VISION_API_KEY=$GOOGLE_VISION_API_KEY \
            --dart-define=NUTRITIONIX_APP_KEY=$NUTRITIONIX_APP_KEY \
            --dart-define=NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID \
            --dart-define=RAPID_API_KEY=$RAPID_API_KEY

    artifacts:
      # iOS unsigned IPA + archive (for debugging)
      - ios/build/Runner-unsigned.ipa
      - ios/build/Runner.xcarchive/**

      # Android
      - build/**/outputs/**/*.apk

      # Logs
      - flutter_drive.log
      - /tmp/xcodebuild_logs/*.log
