workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      groups:
        - env_files
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create .env file
        script: |
          echo "MEALDB_API_KEY=$MEALDB_API_KEY" > .env
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> .env
          echo "GOOGLE_VISION_API_KEY=$GOOGLE_VISION_API_KEY" >> .env
          echo "NUTRITIONIX_APP_KEY=$NUTRITIONIX_APP_KEY" >> .env
          echo "NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID" >> .env
          echo "RAPID_API_KEY=$RAPID_API_KEY" >> .env
          cat .env

      - name: Get Flutter dependencies
        script: flutter packages get

      - name: Build iOS
        script: flutter build ios --debug --simulator

    artifacts:
      - build/ios/**/*.app
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
