name: solar_vitas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  carousel_slider: ^5.0.0
  flutter_riverpod: ^2.4.0
  flutter_localization: ^0.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # Uncomment and to add specific images as needed

    # Translations
    # ==========
    - lib/i18n/
    - assets/i18n/en/
    - assets/i18n/pt/
    - assets/i18n/fr/
    - assets/i18n/it/
    - assets/i18n/de/

    # ==========
    # Feature Images

    # Dashboard and Auth Images
    - assets/images/google_logo.jpg
    - assets/images/facebook_logo.jpg
    - assets/images/welcome_illustration.png
    - assets/images/dashboard/hiit.jpg
    - assets/images/dashboard/abs.jpg

    # ==========
    # Search Section
    - assets/images/search/yoga_sessions/
    - assets/images/search/outdoor_activities/
    - assets/images/search/strength_training/
    - assets/images/search/calisthenics/
    - assets/images/search/meditation/
    - assets/images/search/abs_cardio/

    # Eco Tips Section
    - assets/images/eco_tips/waste_management/
    - assets/images/eco_tips/energy/
    - assets/images/eco_tips/water/
    - assets/images/eco_tips/transport/
    - assets/images/eco_tips/sustainable_products/

    # Health Section
    - assets/images/health/health_profile/
    - assets/images/health/meals/

    # AI Section
    - assets/images/solar_ai/

    # Intro Section
    - assets/images/fitness1.jpg
    - assets/images/fitness2.jpg
    - assets/images/fitness3.jpg

    # - assets/images/logo.png

  # Uncomment this section if you plan to use custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
