name: solar_vitas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  carousel_slider: ^5.0.0
  flutter_riverpod: ^2.4.0
  flutter_localization: ^0.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # Uncomment and add specific images as needed
    - lib/i18n/
    - assets/i18n/en/nav.json
    - assets/i18n/en/dashboard.json
    - assets/i18n/pt/nav.json
    - assets/i18n/pt/dashboard.json
    - assets/i18n/en/eco_tips.json
    - assets/i18n/pt/eco_tips.json
    - assets/images/welcome_illustration.png
    - assets/images/dashboard/hiit.jpg
    - assets/images/dashboard/abs.jpg
    - assets/images/search/yoga_sessions/yoga.jpg
    - assets/images/search/yoga_sessions/yoga-1.jpg
    - assets/images/search/yoga_sessions/yoga-2.jpg
    - assets/images/search/outdoor_activities/running.jpg
    - assets/images/search/outdoor_activities/running-1.jpg
    - assets/images/search/outdoor_activities/running-2.jpg
    - assets/images/search/strength_training/strength.jpg
    - assets/images/search/strength_training/strength-1.jpg
    - assets/images/search/strength_training/strength-2.jpg
    - assets/images/search/calisthenics/calisthenics.jpg
    - assets/images/search/calisthenics/calisthenics-1.jpg
    - assets/images/search/calisthenics/calisthenics-2.jpg
    - assets/images/search/meditation/meditation.jpg
    - assets/images/search/meditation/meditation-1.jpg
    - assets/images/search/meditation/meditation-2.jpg
    - assets/images/search/abs_cardio/abs-1.jpg
    - assets/images/search/abs_cardio/abs-2.jpg
    - assets/images/search/abs_cardio/cardio.jpg
    - assets/images/eco_tips/waste_management/recycle.jpg
    - assets/images/eco_tips/energy/energy.jpg
    - assets/images/eco_tips/water/water.jpg
    - assets/images/eco_tips/transport/transport.jpg
    - assets/images/eco_tips/sustainable_products/eco_clothes.jpg
    - assets/images/eco_tips/sustainable_products/bamboo_bottle.jpg
    - assets/images/eco_tips/sustainable_products/yoga_mat.jpg
    - assets/images/health/health_profile/profile.jpg
    - assets/images/health/meals/meal.jpg
    - assets/images/solar_ai/AI_avatar.jpg
    - assets/images/fitness1.jpg
    - assets/images/fitness2.jpg
    - assets/images/fitness3.jpg

    # - assets/images/logo.png

  # Uncomment this section if you plan to use custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
