name: solar_vitas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  carousel_slider: ^5.0.0
  flutter_riverpod: ^2.4.0
  flutter_localization: ^0.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # Uncomment and add specific images as needed
    - lib/i18n/
    - assets/i18n/en.json
    - assets/i18n/pt.json
    - assets/images/welcome_illustration.png
    - assets/images/hiit.jpg
    - assets/images/abs.jpg
    - assets/images/yoga.jpg
    - assets/images/yoga-1.jpg
    - assets/images/yoga-2.jpg
    - assets/images/running.jpg
    - assets/images/running-1.jpg
    - assets/images/running-2.jpg
    - assets/images/strength.jpg
    - assets/images/strength-1.jpg
    - assets/images/strength-2.jpg
    - assets/images/recycle.jpg
    - assets/images/energy.jpg
    - assets/images/water.jpg
    - assets/images/eco_clothes.jpg
    - assets/images/bamboo_bottle.jpg
    - assets/images/yoga_mat.jpg
    - assets/images/fitness1.jpg
    - assets/images/fitness2.jpg
    - assets/images/fitness3.jpg

    # - assets/images/logo.png

  # Uncomment this section if you plan to use custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
