name: solar_vitas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  fl_chart: ^0.63.0
  uuid: 4.5.1
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  http: ^1.1.2
  http_parser: ^4.0.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.3.0
  path_provider: ^2.1.4
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  carousel_slider: ^5.0.0
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.3
  video_player: ^2.8.1
  logger: ^1.1.0
  logging: ^1.2.0
  retry: ^3.1.2
  lottie: ^3.1.2
  rive: ^0.13.20

  # Notifications
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  timezone: ^0.9.2

  # Health Data Integration
  health: ^11.1.1
  device_info_plus: ^10.1.2

  # Maps and Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.1.3
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.3.2+10
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.3

  # AI providers
  google_generative_ai: ^0.4.6

  # Speech-to-text
  speech_to_text: ^7.1.0

  # Audio
  just_audio: ^0.9.36

  # Payment processing
  pay: ^2.0.0
  in_app_purchase: ^3.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

dependency_overrides:
  # Force speech_to_text v7.1.0 (works around potential v7.2.0 lock issues)
  speech_to_text: 7.1.0
  # Optional override for intl if needed to force consistency
  intl: ^0.20.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/rive/
    - assets/videos/
    - assets/config/
    - assets/apple_pay_payment_profile.json
    - assets/google_pay_payment_profile.json
    - .env # Commented out for CI/CD - using --dart-define instead

    # Translations
    # ==========
    - lib/i18n/
    - assets/i18n/en/
    - assets/i18n/es/
    - assets/i18n/pt/
    - assets/i18n/fr/
    - assets/i18n/it/
    - assets/i18n/de/
    - assets/i18n/ru/
    - assets/i18n/ja/
    - assets/i18n/zh/
    - assets/i18n/hi/

    # ==========
    # Feature Images

    # Dashboard and Auth Images
    - assets/images/google_logo.jpg

    # Dynamic Dashboard Images (explicit file references)
    # Eco Images - Male
    - assets/images/dashboard/Eco/Male/bike.webp
    - assets/images/dashboard/Eco/Male/bottle-recycle.webp
    - assets/images/dashboard/Eco/Male/cycling.webp
    - assets/images/dashboard/Eco/Male/globe-couple.webp
    - assets/images/dashboard/Eco/Male/hiking-climb-up-mountain.webp

    # Eco Images - Female
    - assets/images/dashboard/Eco/Female/bike.webp
    - assets/images/dashboard/Eco/Female/bottle-recycle.webp
    - assets/images/dashboard/Eco/Female/eldery-fitness-smile.webp
    - assets/images/dashboard/Eco/Female/female-nature-exercise.webp
    - assets/images/dashboard/Eco/Female/globe-couple.webp

    # Eco Images - Mixed
    - assets/images/dashboard/Eco/Mixed/bike.webp
    - assets/images/dashboard/Eco/Mixed/bottle-recycle.webp
    - assets/images/dashboard/Eco/Mixed/globe-couple.webp

    # Fitness Images - Male
    - assets/images/dashboard/Fitness/Male/abs.webp
    - assets/images/dashboard/Fitness/Male/bro.webp
    - assets/images/dashboard/Fitness/Male/gym-man.webp
    - assets/images/dashboard/Fitness/Male/hiit.webp
    - assets/images/dashboard/Fitness/Male/weigh-lift.webp

    # Fitness Images - Female
    - assets/images/dashboard/Fitness/Female/abs.webp
    - assets/images/dashboard/Fitness/Female/determined-smiling-young-woman.webp
    - assets/images/dashboard/Fitness/Female/legpress.webp
    - assets/images/dashboard/Fitness/Female/pillates.webp
    - assets/images/dashboard/Fitness/Female/young-athletic-woman-exercising.webp

    # Fitness Images - Mixed
    - assets/images/dashboard/Fitness/Mixed/abs.webp
    - assets/images/dashboard/Fitness/Mixed/determined-smiling-young-woman.webp
    - assets/images/dashboard/Fitness/Mixed/hiit.webp
    - assets/images/dashboard/Fitness/Mixed/jump.webp
    - assets/images/dashboard/Fitness/Mixed/rope.webp

    # Nutrition Images
    - assets/images/dashboard/Nutrition/mixed/black-girl-smile-pear.webp
    - assets/images/dashboard/Nutrition/mixed/black-white-sharing.webp
    - assets/images/dashboard/Nutrition/mixed/burger-healthy.webp
    - assets/images/dashboard/Nutrition/mixed/mixed-people-healthy.webp
    - assets/images/dashboard/Nutrition/mixed/mum-daughther-cooking.webp
    - assets/images/dashboard/Nutrition/mixed/shooping.webp

    # Mindfulness Images
    - assets/images/dashboard/Mindfullness/mixed/mediation-couple-black.webp
    - assets/images/dashboard/Mindfullness/mixed/mediation-couple.webp
    - assets/images/dashboard/Mindfullness/mixed/mediation-inside.webp
    - assets/images/dashboard/Mindfullness/mixed/mediation-outdoor.webp
    - assets/images/dashboard/Mindfullness/mixed/mediation-sunset.webp
    - assets/images/dashboard/Mindfullness/mixed/mediation.webp

    # Community Images
    - assets/images/dashboard/Community/community-message.webp
    - assets/images/dashboard/Community/community-play.webp
    - assets/images/dashboard/Community/eldery-community.webp
    - assets/images/dashboard/Community/mixed-community.webp
    - assets/images/dashboard/Community/run-community.webp
    - assets/images/dashboard/Community/silhouette-of-climbers-who-climb.webp

    # Adventure Images
    - assets/images/dashboard/Adventure/Mixed/dog-friend.webp
    - assets/images/dashboard/Adventure/Mixed/mountain-couple.webp
    - assets/images/dashboard/Adventure/Mixed/mountain-man.webp
    - assets/images/dashboard/Adventure/Mixed/mountain-women.webp
    - assets/images/dashboard/Adventure/Mixed/sunsuet-adventure.webp

    # ==========
    # Search Section
    - assets/images/search/yoga_sessions/
    - assets/images/search/outdoor_activities/
    - assets/images/search/strength_training/
    - assets/images/search/calisthenics/
    - assets/images/search/meditation/
    - assets/images/search/abs_cardio/

    # Eco Tips Section
    - assets/images/eco_tips/waste_management/
    - assets/images/eco_tips/energy/
    - assets/images/eco_tips/water/
    - assets/images/eco_tips/transport/
    - assets/images/eco_tips/sustainable_products/

    # Health Section
    - assets/images/health/health_profile/
    - assets/images/health/meals/

    # AI Section
    - assets/images/solar_ai/

    # Intro Section

    # Audio files for onboarding
    - assets/audio/

    # - assets/images/logo.png

  # Uncomment this section if you plan to use custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
