name: solar_vitas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0 # Use the appropriate version for your project
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  fl_chart: ^0.63.0
  uuid: ^3.0.7
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  http: ^1.1.2
  http_parser: ^4.0.2
  google_fonts: ^6.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  carousel_slider: ^5.0.0
  flutter_riverpod: ^2.4.0
  video_player: ^2.8.1
  logger: ^1.1.0
  logging: ^1.2.0
  retry: ^3.1.2

  #Notifictions
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  timezone: ^0.9.2

  # Firebase dependencies
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/

    # env file
    - .env

    # Translations
    # ==========
    - lib/i18n/
    - assets/i18n/en/
    - assets/i18n/es/
    - assets/i18n/pt/
    - assets/i18n/fr/
    - assets/i18n/it/
    - assets/i18n/de/

    # ==========
    # Feature Images

    # Dashboard and Auth Images
    - assets/images/google_logo.jpg
    - assets/images/facebook_logo.jpg
    - assets/images/welcome_illustration.png
    - assets/images/dashboard/hiit.jpg
    - assets/images/dashboard/abs.jpg

    # ==========
    # Search Section
    - assets/images/search/yoga_sessions/
    - assets/images/search/outdoor_activities/
    - assets/images/search/strength_training/
    - assets/images/search/calisthenics/
    - assets/images/search/meditation/
    - assets/images/search/abs_cardio/

    # Eco Tips Section
    - assets/images/eco_tips/waste_management/
    - assets/images/eco_tips/energy/
    - assets/images/eco_tips/water/
    - assets/images/eco_tips/transport/
    - assets/images/eco_tips/sustainable_products/

    # Health Section
    - assets/images/health/health_profile/
    - assets/images/health/meals/

    # AI Section
    - assets/images/solar_ai/

    # Intro Section
    - assets/images/fitness1.jpg
    - assets/images/fitness2.jpg
    - assets/images/fitness3.jpg

    # - assets/images/logo.png

  # Uncomment this section if you plan to use custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
