/// Comprehensive nutrition database for meal ingredients
/// Contains nutritional values per 100g for all TheMealDB ingredients
class NutritionDatabase {
  /// Get the complete nutrition database
  /// Returns a map of ingredient names to their nutritional values per 100g
  static Map<String, Map<String, double>> getDatabase() {
    return {
      // Proteins (per 100g)
      'chicken breast': {'calories': 165, 'protein': 31, 'carbs': 0, 'fat': 3.6},
      'chicken': {'calories': 239, 'protein': 27, 'carbs': 0, 'fat': 14},
      'beef': {'calories': 250, 'protein': 26, 'carbs': 0, 'fat': 17},
      'pork': {'calories': 242, 'protein': 27, 'carbs': 0, 'fat': 14},
      'lamb': {'calories': 294, 'protein': 25, 'carbs': 0, 'fat': 21},
      'salmon': {'calories': 208, 'protein': 20, 'carbs': 0, 'fat': 13},
      'cod': {'calories': 82, 'protein': 18, 'carbs': 0, 'fat': 0.7},
      'tuna': {'calories': 132, 'protein': 28, 'carbs': 0, 'fat': 1},
      'prawns': {'calories': 99, 'protein': 18, 'carbs': 0.9, 'fat': 1.4},
      'king prawns': {'calories': 99, 'protein': 18, 'carbs': 0.9, 'fat': 1.4},
      'shrimp': {'calories': 99, 'protein': 18, 'carbs': 0.9, 'fat': 1.4},
      'eggs': {'calories': 155, 'protein': 13, 'carbs': 1.1, 'fat': 11},
      'egg': {'calories': 155, 'protein': 13, 'carbs': 1.1, 'fat': 11},
      
      // Dairy
      'milk': {'calories': 42, 'protein': 3.4, 'carbs': 5, 'fat': 1},
      'cheese': {'calories': 402, 'protein': 25, 'carbs': 1.3, 'fat': 33},
      'parmesan': {'calories': 431, 'protein': 38, 'carbs': 4.1, 'fat': 29},
      'butter': {'calories': 717, 'protein': 0.9, 'carbs': 0.1, 'fat': 81},
      'unsalted butter': {'calories': 717, 'protein': 0.9, 'carbs': 0.1, 'fat': 81},
      'cream': {'calories': 345, 'protein': 2.8, 'carbs': 3.2, 'fat': 37},
      'heavy cream': {'calories': 345, 'protein': 2.8, 'carbs': 3.2, 'fat': 37},
      'sour cream': {'calories': 198, 'protein': 2.4, 'carbs': 4.6, 'fat': 19},
      'fromage frais': {'calories': 113, 'protein': 7.5, 'carbs': 4, 'fat': 8},
      'yogurt': {'calories': 59, 'protein': 10, 'carbs': 3.6, 'fat': 0.4},
      
      // Grains and Starches
      'rice': {'calories': 130, 'protein': 2.7, 'carbs': 28, 'fat': 0.3},
      'pasta': {'calories': 131, 'protein': 5, 'carbs': 25, 'fat': 1.1},
      'linguine pasta': {'calories': 131, 'protein': 5, 'carbs': 25, 'fat': 1.1},
      'fettuccine': {'calories': 131, 'protein': 5, 'carbs': 25, 'fat': 1.1},
      'bread': {'calories': 265, 'protein': 9, 'carbs': 49, 'fat': 3.2},
      'flour': {'calories': 364, 'protein': 10, 'carbs': 76, 'fat': 1},
      'potatoes': {'calories': 77, 'protein': 2, 'carbs': 17, 'fat': 0.1},
      'potato': {'calories': 77, 'protein': 2, 'carbs': 17, 'fat': 0.1},
      
      // Vegetables
      'onion': {'calories': 40, 'protein': 1.1, 'carbs': 9.3, 'fat': 0.1},
      'garlic': {'calories': 149, 'protein': 6.4, 'carbs': 33, 'fat': 0.5},
      'garlic clove': {'calories': 149, 'protein': 6.4, 'carbs': 33, 'fat': 0.5},
      'tomato': {'calories': 18, 'protein': 0.9, 'carbs': 3.9, 'fat': 0.2},
      'tomatoes': {'calories': 18, 'protein': 0.9, 'carbs': 3.9, 'fat': 0.2},
      'cherry tomatoes': {'calories': 18, 'protein': 0.9, 'carbs': 3.9, 'fat': 0.2},
      'carrots': {'calories': 41, 'protein': 0.9, 'carbs': 10, 'fat': 0.2},
      'pepper': {'calories': 31, 'protein': 1, 'carbs': 7, 'fat': 0.3},
      'bell peppers': {'calories': 31, 'protein': 1, 'carbs': 7, 'fat': 0.3},
      'green pepper': {'calories': 31, 'protein': 1, 'carbs': 7, 'fat': 0.3},
      'red pepper': {'calories': 31, 'protein': 1, 'carbs': 7, 'fat': 0.3},
      'yellow pepper': {'calories': 31, 'protein': 1, 'carbs': 7, 'fat': 0.3},
      'mushrooms': {'calories': 22, 'protein': 3.1, 'carbs': 3.3, 'fat': 0.3},
      'broccoli': {'calories': 34, 'protein': 2.8, 'carbs': 7, 'fat': 0.4},
      'spinach': {'calories': 23, 'protein': 2.9, 'carbs': 3.6, 'fat': 0.4},
      'lettuce': {'calories': 15, 'protein': 1.4, 'carbs': 2.9, 'fat': 0.2},
      'cucumber': {'calories': 16, 'protein': 0.7, 'carbs': 4, 'fat': 0.1},
      'courgette': {'calories': 17, 'protein': 1.2, 'carbs': 3.1, 'fat': 0.3},
      'aubergine': {'calories': 25, 'protein': 1, 'carbs': 6, 'fat': 0.2},
      'cabbage': {'calories': 25, 'protein': 1.3, 'carbs': 6, 'fat': 0.1},
      'cauliflower': {'calories': 25, 'protein': 1.9, 'carbs': 5, 'fat': 0.3},
      'celery': {'calories': 16, 'protein': 0.7, 'carbs': 3, 'fat': 0.2},
      'leeks': {'calories': 61, 'protein': 1.5, 'carbs': 14, 'fat': 0.3},
      'sweetcorn': {'calories': 86, 'protein': 3.3, 'carbs': 19, 'fat': 1.4},
      'peas': {'calories': 81, 'protein': 5.4, 'carbs': 14, 'fat': 0.4},
      'beans': {'calories': 31, 'protein': 1.8, 'carbs': 7, 'fat': 0.1},
      'green beans': {'calories': 31, 'protein': 1.8, 'carbs': 7, 'fat': 0.1},
      'asparagus': {'calories': 20, 'protein': 2.2, 'carbs': 3.9, 'fat': 0.1},
      'beetroot': {'calories': 43, 'protein': 1.6, 'carbs': 10, 'fat': 0.2},
      'radish': {'calories': 16, 'protein': 0.7, 'carbs': 3.4, 'fat': 0.1},
      'turnips': {'calories': 28, 'protein': 0.9, 'carbs': 6, 'fat': 0.1},
      'parsnip': {'calories': 75, 'protein': 1.2, 'carbs': 18, 'fat': 0.3},
      'sweet potato': {'calories': 86, 'protein': 1.6, 'carbs': 20, 'fat': 0.1},
      'avocado': {'calories': 160, 'protein': 2, 'carbs': 9, 'fat': 15},
      'artichoke': {'calories': 47, 'protein': 3.3, 'carbs': 11, 'fat': 0.2},
      'okra': {'calories': 33, 'protein': 1.9, 'carbs': 7, 'fat': 0.2},
      'fennel': {'calories': 31, 'protein': 1.2, 'carbs': 7, 'fat': 0.2},
      'watercress': {'calories': 11, 'protein': 2.3, 'carbs': 1.3, 'fat': 0.1},
      'rocket': {'calories': 25, 'protein': 2.6, 'carbs': 3.7, 'fat': 0.7},
      'spring onions': {'calories': 32, 'protein': 1.8, 'carbs': 7.3, 'fat': 0.2},
      'red onion': {'calories': 40, 'protein': 1.1, 'carbs': 9.3, 'fat': 0.1},
      'white onion': {'calories': 40, 'protein': 1.1, 'carbs': 9.3, 'fat': 0.1},
      'shallots': {'calories': 72, 'protein': 2.5, 'carbs': 17, 'fat': 0.1},
      
      // Fruits
      'apple': {'calories': 52, 'protein': 0.3, 'carbs': 14, 'fat': 0.2},
      'orange': {'calories': 47, 'protein': 0.9, 'carbs': 12, 'fat': 0.1},
      'lemon': {'calories': 29, 'protein': 1.1, 'carbs': 9, 'fat': 0.3},
      'lime': {'calories': 30, 'protein': 0.7, 'carbs': 11, 'fat': 0.2},
      'grape': {'calories': 69, 'protein': 0.7, 'carbs': 18, 'fat': 0.2},
      'strawberry': {'calories': 32, 'protein': 0.7, 'carbs': 8, 'fat': 0.3},
      'blueberries': {'calories': 57, 'protein': 0.7, 'carbs': 14, 'fat': 0.3},
      'raspberries': {'calories': 52, 'protein': 1.2, 'carbs': 12, 'fat': 0.7},
      'blackberries': {'calories': 43, 'protein': 1.4, 'carbs': 10, 'fat': 0.5},
      'peach': {'calories': 39, 'protein': 0.9, 'carbs': 10, 'fat': 0.3},
      'pear': {'calories': 57, 'protein': 0.4, 'carbs': 15, 'fat': 0.1},
      'plum': {'calories': 46, 'protein': 0.7, 'carbs': 11, 'fat': 0.3},
      'cherry': {'calories': 63, 'protein': 1.1, 'carbs': 16, 'fat': 0.2},
      'apricot': {'calories': 48, 'protein': 1.4, 'carbs': 11, 'fat': 0.4},
      'pineapple': {'calories': 50, 'protein': 0.5, 'carbs': 13, 'fat': 0.1},
      'mango': {'calories': 60, 'protein': 0.8, 'carbs': 15, 'fat': 0.4},
      'papaya': {'calories': 43, 'protein': 0.5, 'carbs': 11, 'fat': 0.3},
      'kiwi': {'calories': 61, 'protein': 1.1, 'carbs': 15, 'fat': 0.5},
      'pomegranate': {'calories': 83, 'protein': 1.7, 'carbs': 19, 'fat': 1.2},
      'cranberries': {'calories': 46, 'protein': 0.5, 'carbs': 12, 'fat': 0.1},
      'dates': {'calories': 277, 'protein': 1.8, 'carbs': 75, 'fat': 0.2},
      'figs': {'calories': 74, 'protein': 0.8, 'carbs': 19, 'fat': 0.3},
      'raisins': {'calories': 299, 'protein': 3.1, 'carbs': 79, 'fat': 0.5},
      
      // Herbs and Spices
      'basil': {'calories': 22, 'protein': 3.2, 'carbs': 2.6, 'fat': 0.6},
      'oregano': {'calories': 265, 'protein': 9, 'carbs': 69, 'fat': 4.3},
      'thyme': {'calories': 101, 'protein': 5.6, 'carbs': 24, 'fat': 1.7},
      'rosemary': {'calories': 131, 'protein': 3.3, 'carbs': 20, 'fat': 5.9},
      'sage': {'calories': 315, 'protein': 10.6, 'carbs': 61, 'fat': 12.8},
      'parsley': {'calories': 36, 'protein': 3, 'carbs': 6.3, 'fat': 0.8},
      'coriander': {'calories': 23, 'protein': 2.1, 'carbs': 3.7, 'fat': 0.5},
      'mint': {'calories': 70, 'protein': 3.8, 'carbs': 14.9, 'fat': 0.9},
      'dill': {'calories': 43, 'protein': 3.5, 'carbs': 7, 'fat': 1.1},
      'chives': {'calories': 30, 'protein': 3.3, 'carbs': 4.4, 'fat': 0.7},
      'ginger': {'calories': 80, 'protein': 1.8, 'carbs': 18, 'fat': 0.8},
      'turmeric': {'calories': 354, 'protein': 7.8, 'carbs': 65, 'fat': 10},
      'cumin': {'calories': 375, 'protein': 18, 'carbs': 44, 'fat': 22},
      'coriander seeds': {'calories': 298, 'protein': 12, 'carbs': 55, 'fat': 17},
      'paprika': {'calories': 282, 'protein': 14, 'carbs': 54, 'fat': 13},
      'cayenne pepper': {'calories': 318, 'protein': 12, 'carbs': 57, 'fat': 17},
      'black pepper': {'calories': 251, 'protein': 10, 'carbs': 64, 'fat': 3.3},
      'white pepper': {'calories': 296, 'protein': 11, 'carbs': 69, 'fat': 2.1},
      'nutmeg': {'calories': 525, 'protein': 5.8, 'carbs': 49, 'fat': 36},
      'cinnamon': {'calories': 247, 'protein': 4, 'carbs': 81, 'fat': 1.2},
      'cardamom': {'calories': 311, 'protein': 11, 'carbs': 68, 'fat': 6.7},
      'cloves': {'calories': 274, 'protein': 6, 'carbs': 65, 'fat': 13},
      'allspice': {'calories': 263, 'protein': 6.1, 'carbs': 72, 'fat': 8.7},
      'star anise': {'calories': 337, 'protein': 18, 'carbs': 50, 'fat': 16},
      'bay leaves': {'calories': 313, 'protein': 7.6, 'carbs': 75, 'fat': 8.4},
      'vanilla': {'calories': 288, 'protein': 0.1, 'carbs': 13, 'fat': 0.1},
      'saffron': {'calories': 310, 'protein': 11, 'carbs': 65, 'fat': 5.9},
      
      // Nuts and Seeds
      'almonds': {'calories': 579, 'protein': 21, 'carbs': 22, 'fat': 50},
      'walnuts': {'calories': 654, 'protein': 15, 'carbs': 14, 'fat': 65},
      'pecans': {'calories': 691, 'protein': 9.2, 'carbs': 14, 'fat': 72},
      'cashews': {'calories': 553, 'protein': 18, 'carbs': 30, 'fat': 44},
      'pistachios': {'calories': 560, 'protein': 20, 'carbs': 28, 'fat': 45},
      'hazelnuts': {'calories': 628, 'protein': 15, 'carbs': 17, 'fat': 61},
      'brazil nuts': {'calories': 659, 'protein': 14, 'carbs': 12, 'fat': 67},
      'pine nuts': {'calories': 673, 'protein': 14, 'carbs': 13, 'fat': 68},
      'macadamia nuts': {'calories': 718, 'protein': 7.9, 'carbs': 14, 'fat': 76},
      'sunflower seeds': {'calories': 584, 'protein': 21, 'carbs': 20, 'fat': 51},
      'pumpkin seeds': {'calories': 559, 'protein': 30, 'carbs': 11, 'fat': 49},
      'sesame seeds': {'calories': 573, 'protein': 18, 'carbs': 23, 'fat': 50},
      'flax seeds': {'calories': 534, 'protein': 18, 'carbs': 29, 'fat': 42},
      'chia seeds': {'calories': 486, 'protein': 17, 'carbs': 42, 'fat': 31},
      
      // Oils and Fats
      'olive oil': {'calories': 884, 'protein': 0, 'carbs': 0, 'fat': 100},
      'coconut oil': {'calories': 862, 'protein': 0, 'carbs': 0, 'fat': 99},
      'vegetable oil': {'calories': 884, 'protein': 0, 'carbs': 0, 'fat': 100},
      'canola oil': {'calories': 884, 'protein': 0, 'carbs': 0, 'fat': 100},
      'sunflower oil': {'calories': 884, 'protein': 0, 'carbs': 0, 'fat': 100},
      'sesame oil': {'calories': 884, 'protein': 0, 'carbs': 0, 'fat': 100},
      'avocado oil': {'calories': 884, 'protein': 0, 'carbs': 0, 'fat': 100},
      
      // Seafood
      'mackerel': {'calories': 205, 'protein': 19, 'carbs': 0, 'fat': 14},
      'sardines': {'calories': 208, 'protein': 25, 'carbs': 0, 'fat': 11},
      'anchovies': {'calories': 131, 'protein': 20, 'carbs': 0, 'fat': 4.8},
      'trout': {'calories': 148, 'protein': 21, 'carbs': 0, 'fat': 6.6},
      'halibut': {'calories': 91, 'protein': 19, 'carbs': 0, 'fat': 1.3},
      'sole': {'calories': 70, 'protein': 16, 'carbs': 0, 'fat': 0.4},
      'sea bass': {'calories': 97, 'protein': 18, 'carbs': 0, 'fat': 2},
      'sea bream': {'calories': 96, 'protein': 19, 'carbs': 0, 'fat': 1.2},
      'mussels': {'calories': 86, 'protein': 12, 'carbs': 7, 'fat': 2.2},
      'clams': {'calories': 148, 'protein': 26, 'carbs': 5, 'fat': 2},
      'oysters': {'calories': 81, 'protein': 9, 'carbs': 5, 'fat': 2.3},
      'scallops': {'calories': 88, 'protein': 17, 'carbs': 2, 'fat': 0.8},
      'crab': {'calories': 87, 'protein': 18, 'carbs': 0, 'fat': 1.1},
      'lobster': {'calories': 77, 'protein': 16, 'carbs': 0, 'fat': 0.7},
      'squid': {'calories': 92, 'protein': 16, 'carbs': 3, 'fat': 1.4},
      'octopus': {'calories': 82, 'protein': 15, 'carbs': 2.2, 'fat': 1},
      
      // Condiments and Sauces
      'soy sauce': {'calories': 8, 'protein': 1.3, 'carbs': 0.8, 'fat': 0},
      'worcestershire sauce': {'calories': 78, 'protein': 0, 'carbs': 19, 'fat': 0},
      'tabasco sauce': {'calories': 12, 'protein': 1.3, 'carbs': 0.8, 'fat': 0.8},
      'tomato paste': {'calories': 82, 'protein': 4.3, 'carbs': 19, 'fat': 0.2},
      'tomato puree': {'calories': 38, 'protein': 1.6, 'carbs': 9, 'fat': 0.2},
      'balsamic vinegar': {'calories': 88, 'protein': 0.5, 'carbs': 17, 'fat': 0},
      'white wine vinegar': {'calories': 18, 'protein': 0, 'carbs': 0.04, 'fat': 0},
      'apple cider vinegar': {'calories': 22, 'protein': 0, 'carbs': 0.9, 'fat': 0},
      'dijon mustard': {'calories': 66, 'protein': 3.7, 'carbs': 7.2, 'fat': 3.4},
      'wholegrain mustard': {'calories': 140, 'protein': 7, 'carbs': 12, 'fat': 8},
      'honey': {'calories': 304, 'protein': 0.3, 'carbs': 82, 'fat': 0},
      'sugar': {'calories': 387, 'protein': 0, 'carbs': 100, 'fat': 0},
      'brown sugar': {'calories': 380, 'protein': 0, 'carbs': 98, 'fat': 0},
      'salt': {'calories': 0, 'protein': 0, 'carbs': 0, 'fat': 0},
      'sea salt': {'calories': 0, 'protein': 0, 'carbs': 0, 'fat': 0},
      'stock cube': {'calories': 40, 'protein': 3, 'carbs': 3, 'fat': 2},
      'chicken stock': {'calories': 86, 'protein': 6, 'carbs': 8.5, 'fat': 2.9},
      'vegetable stock': {'calories': 12, 'protein': 0.4, 'carbs': 2.8, 'fat': 0.1},
      'beef stock': {'calories': 6, 'protein': 1, 'carbs': 0, 'fat': 0.2},
      
      // Other Proteins
      'duck': {'calories': 337, 'protein': 19, 'carbs': 0, 'fat': 28},
      'turkey': {'calories': 135, 'protein': 30, 'carbs': 0, 'fat': 0.7},
      'venison': {'calories': 158, 'protein': 30, 'carbs': 0, 'fat': 3.2},
      'rabbit': {'calories': 173, 'protein': 33, 'carbs': 0, 'fat': 3.5},
      'pheasant': {'calories': 181, 'protein': 32, 'carbs': 0, 'fat': 5.2},
      'quail': {'calories': 227, 'protein': 25, 'carbs': 0, 'fat': 14},
      'veal': {'calories': 172, 'protein': 32, 'carbs': 0, 'fat': 4.6},
      'bacon': {'calories': 541, 'protein': 37, 'carbs': 1.4, 'fat': 42},
      'ham': {'calories': 145, 'protein': 21, 'carbs': 1.5, 'fat': 5.5},
      'sausage': {'calories': 301, 'protein': 13, 'carbs': 4, 'fat': 26},
      'chorizo': {'calories': 455, 'protein': 24, 'carbs': 2, 'fat': 38},
      'salami': {'calories': 336, 'protein': 22, 'carbs': 1, 'fat': 27},
      'prosciutto': {'calories': 217, 'protein': 30, 'carbs': 0, 'fat': 9.8},
      'pancetta': {'calories': 563, 'protein': 21, 'carbs': 0, 'fat': 53},
      'black pudding': {'calories': 379, 'protein': 15, 'carbs': 18, 'fat': 27},
      'kidney': {'calories': 130, 'protein': 25, 'carbs': 0, 'fat': 3.2},
      'liver': {'calories': 175, 'protein': 26, 'carbs': 5, 'fat': 5},
      
      // Legumes
      'green red lentils': {'calories': 116, 'protein': 9, 'carbs': 20, 'fat': 0.4},
      'sauerkraut': {'calories': 19, 'protein': 0.9, 'carbs': 4.3, 'fat': 0.1},
      
      // Beverages and liquids
      'maple syrup': {'calories': 260, 'protein': 0, 'carbs': 67, 'fat': 0.4},
      'stout': {'calories': 37, 'protein': 0.4, 'carbs': 3.2, 'fat': 0},
      'white wine': {'calories': 82, 'protein': 0.1, 'carbs': 2.6, 'fat': 0},
      
      // Final additions for 100% coverage
      'banana': {'calories': 89, 'protein': 1.1, 'carbs': 23, 'fat': 0.3},
      'chili powder': {'calories': 282, 'protein': 13.5, 'carbs': 50, 'fat': 12},
      'goat meat': {'calories': 109, 'protein': 21.4, 'carbs': 0, 'fat': 2.3},
      'kale': {'calories': 35, 'protein': 2.9, 'carbs': 4.4, 'fat': 1.5},
      
      // Additional missing ingredients found in meal processing
      'ackee': {'calories': 151, 'protein': 2.9, 'carbs': 9.8, 'fat': 15.2},
      'ancho chillies': {'calories': 281, 'protein': 11.9, 'carbs': 50.4, 'fat': 8.2},
      'anchovy fillet': {'calories': 131, 'protein': 20, 'carbs': 0, 'fat': 4.8},
      'apricot jam': {'calories': 241, 'protein': 0.4, 'carbs': 62, 'fat': 0.1},
      'baguette': {'calories': 272, 'protein': 9.4, 'carbs': 55, 'fat': 2.3},
      'baked beans': {'calories': 155, 'protein': 5.2, 'carbs': 22, 'fat': 5.4},
      'bicarbonate of soda': {'calories': 0, 'protein': 0, 'carbs': 0, 'fat': 0},
      'biryani masala': {'calories': 375, 'protein': 11, 'carbs': 44, 'fat': 15},
      'borlotti beans': {'calories': 127, 'protein': 9, 'carbs': 23, 'fat': 0.5},
      'bouquet garni': {'calories': 5, 'protein': 0.3, 'carbs': 1, 'fat': 0.1},
      'brandy': {'calories': 225, 'protein': 0, 'carbs': 0, 'fat': 0},
      'broad beans': {'calories': 88, 'protein': 7.9, 'carbs': 11.7, 'fat': 0.8},
      'brown lentils': {'calories': 116, 'protein': 9, 'carbs': 20, 'fat': 0.4},
      'bulgur wheat': {'calories': 342, 'protein': 12.3, 'carbs': 75.9, 'fat': 1.3},
      'candied peel': {'calories': 322, 'protein': 0.2, 'carbs': 82, 'fat': 0.3},
      'capers': {'calories': 23, 'protein': 2.4, 'carbs': 4.9, 'fat': 0.9},
      'caramel': {'calories': 382, 'protein': 0.1, 'carbs': 76, 'fat': 8.1},
      'caramel sauce': {'calories': 335, 'protein': 0.8, 'carbs': 74, 'fat': 8.2},
      'cashew nuts': {'calories': 553, 'protein': 18, 'carbs': 30, 'fat': 44},
      'celeriac': {'calories': 42, 'protein': 1.5, 'carbs': 9.2, 'fat': 0.3},
      'chestnut mushroom': {'calories': 28, 'protein': 2.4, 'carbs': 4.3, 'fat': 0.5},
      'chestnuts': {'calories': 213, 'protein': 2.4, 'carbs': 45, 'fat': 2.3},
      'chickpeas': {'calories': 164, 'protein': 8.9, 'carbs': 27, 'fat': 2.6},
      'chocolate chips': {'calories': 479, 'protein': 4.2, 'carbs': 57, 'fat': 28},
      'christmas pudding': {'calories': 329, 'protein': 3.5, 'carbs': 62, 'fat': 8.8},
      'ciabatta': {'calories': 271, 'protein': 9, 'carbs': 51, 'fat': 3.8},
      'cider': {'calories': 50, 'protein': 0.1, 'carbs': 6, 'fat': 0},
      'cilantro': {'calories': 23, 'protein': 2.1, 'carbs': 3.7, 'fat': 0.5},
      'cocoa': {'calories': 228, 'protein': 19.6, 'carbs': 57.9, 'fat': 13.7},
      'cooking wine': {'calories': 123, 'protein': 0.1, 'carbs': 3.8, 'fat': 0},
      'couscous': {'calories': 112, 'protein': 3.8, 'carbs': 23, 'fat': 0.2},
      'creme fraiche': {'calories': 292, 'protein': 2.4, 'carbs': 2.9, 'fat': 30},
      'currants': {'calories': 283, 'protein': 4.6, 'carbs': 69, 'fat': 0.4},
      'curry powder': {'calories': 325, 'protein': 14.3, 'carbs': 58, 'fat': 14},
      'custard': {'calories': 126, 'protein': 3.4, 'carbs': 17, 'fat': 5.1},
      'custard powder': {'calories': 354, 'protein': 0.6, 'carbs': 92, 'fat': 0.5},
      'dark chocolate': {'calories': 546, 'protein': 4.9, 'carbs': 61, 'fat': 31},
      'dark chocolate chips': {'calories': 501, 'protein': 4.2, 'carbs': 57, 'fat': 29},
      'dark rum': {'calories': 231, 'protein': 0, 'carbs': 0, 'fat': 0},
      'desiccated coconut': {'calories': 660, 'protein': 6.9, 'carbs': 24, 'fat': 64},
      'doubanjiang': {'calories': 140, 'protein': 12, 'carbs': 16, 'fat': 6},
      'dried apricots': {'calories': 241, 'protein': 3.4, 'carbs': 63, 'fat': 0.5},
      'dried fruit': {'calories': 249, 'protein': 2.2, 'carbs': 66, 'fat': 0.4},
      'dried oregano': {'calories': 265, 'protein': 9, 'carbs': 69, 'fat': 4.3},
      'duck legs': {'calories': 337, 'protein': 19, 'carbs': 0, 'fat': 28},
      'duck sauce': {'calories': 91, 'protein': 0.2, 'carbs': 23, 'fat': 0.1},
      'enchilada sauce': {'calories': 34, 'protein': 1.1, 'carbs': 7.8, 'fat': 0.2},
      'english muffins': {'calories': 227, 'protein': 8.7, 'carbs': 44, 'fat': 2.1},
      'fajita seasoning': {'calories': 314, 'protein': 10.7, 'carbs': 64, 'fat': 6.5},
      'farfalle': {'calories': 131, 'protein': 5, 'carbs': 25, 'fat': 1.1},
      'fenugreek': {'calories': 323, 'protein': 23, 'carbs': 58, 'fat': 6.4},
      'fermented black beans': {'calories': 130, 'protein': 11, 'carbs': 23, 'fat': 0.9},
      'feta': {'calories': 264, 'protein': 14, 'carbs': 4.1, 'fat': 21},
      'filo pastry': {'calories': 299, 'protein': 8.7, 'carbs': 51, 'fat': 6.6},
      'french lentils': {'calories': 116, 'protein': 9, 'carbs': 20, 'fat': 0.4},
      'fresh basil': {'calories': 22, 'protein': 3.2, 'carbs': 2.6, 'fat': 0.6},
      'fruit mix': {'calories': 60, 'protein': 0.8, 'carbs': 16, 'fat': 0.2},
      'garam masala': {'calories': 379, 'protein': 14, 'carbs': 65, 'fat': 14},
      'gelatine leafs': {'calories': 335, 'protein': 84, 'carbs': 0, 'fat': 0.1},
      'ghee': {'calories': 900, 'protein': 0, 'carbs': 0, 'fat': 100},
      'glace cherry': {'calories': 251, 'protein': 0.2, 'carbs': 68, 'fat': 0.1},
      'gochujang': {'calories': 240, 'protein': 5, 'carbs': 47, 'fat': 2.5},
      'golden syrup': {'calories': 304, 'protein': 0.4, 'carbs': 79, 'fat': 0},
      'goose fat': {'calories': 900, 'protein': 0, 'carbs': 0, 'fat': 100},
      'grand marnier': {'calories': 153, 'protein': 0, 'carbs': 6.5, 'fat': 0},
      'gruyere': {'calories': 413, 'protein': 29, 'carbs': 0.4, 'fat': 32},
      'gruyère': {'calories': 413, 'protein': 29, 'carbs': 0.4, 'fat': 32},
      'haddock': {'calories': 90, 'protein': 20, 'carbs': 0, 'fat': 0.8},
      'hard taco shells': {'calories': 485, 'protein': 7.3, 'carbs': 61, 'fat': 23},
      'haricot beans': {'calories': 127, 'protein': 8.7, 'carbs': 23, 'fat': 0.5},
      'harissa spice': {'calories': 70, 'protein': 3.7, 'carbs': 11, 'fat': 2.3},
      'hazlenuts': {'calories': 628, 'protein': 15, 'carbs': 17, 'fat': 61},
      'herring': {'calories': 158, 'protein': 18, 'carbs': 0, 'fat': 9},
      'horseradish': {'calories': 48, 'protein': 1.2, 'carbs': 11, 'fat': 0.7},
      'italian seasoning': {'calories': 259, 'protein': 10.6, 'carbs': 55, 'fat': 5.2},
      'jalapeno': {'calories': 29, 'protein': 0.9, 'carbs': 6.5, 'fat': 0.4},
      'jam': {'calories': 278, 'protein': 0.4, 'carbs': 69, 'fat': 0.1},
      'jerusalem artichokes': {'calories': 73, 'protein': 2, 'carbs': 17, 'fat': 0.01},
      'khus khus': {'calories': 525, 'protein': 18, 'carbs': 29, 'fat': 44},
      'kidney beans': {'calories': 127, 'protein': 8.7, 'carbs': 23, 'fat': 0.5},
      'lard': {'calories': 902, 'protein': 0, 'carbs': 0, 'fat': 100},
      'macaroni': {'calories': 131, 'protein': 5, 'carbs': 25, 'fat': 1.1},
      'madras paste': {'calories': 140, 'protein': 6, 'carbs': 20, 'fat': 5},
      'mars bar': {'calories': 449, 'protein': 4.1, 'carbs': 68, 'fat': 17},
      'marzipan': {'calories': 458, 'protein': 9.7, 'carbs': 67, 'fat': 18},
      'mascarpone': {'calories': 429, 'protein': 4.8, 'carbs': 4.1, 'fat': 44},
      'massaman curry paste': {'calories': 165, 'protein': 4.2, 'carbs': 19, 'fat': 8.5},
      'medjool dates': {'calories': 277, 'protein': 1.8, 'carbs': 75, 'fat': 0.2},
      'meringue nests': {'calories': 379, 'protein': 8.8, 'carbs': 95, 'fat': 0.2},
      'mincemeat': {'calories': 274, 'protein': 1.7, 'carbs': 62, 'fat': 4.6},
      'miniature marshmallows': {'calories': 318, 'protein': 1.8, 'carbs': 81, 'fat': 0.2},
      'mirin': {'calories': 241, 'protein': 0.12, 'carbs': 43, 'fat': 0},
      'mixed grain': {'calories': 330, 'protein': 13, 'carbs': 70, 'fat': 2.5},
      'mixed peel': {'calories': 314, 'protein': 0.9, 'carbs': 81, 'fat': 0.6},
      'mixed spice': {'calories': 272, 'protein': 6.8, 'carbs': 68, 'fat': 7},
      'monkfish': {'calories': 76, 'protein': 14.5, 'carbs': 0, 'fat': 1.5},
      'mozzarella': {'calories': 300, 'protein': 22, 'carbs': 2.2, 'fat': 22},
      'mozzarella balls': {'calories': 300, 'protein': 22, 'carbs': 2.2, 'fat': 22},
      'mulukhiyah': {'calories': 58, 'protein': 4.8, 'carbs': 10, 'fat': 0.7},
      'noodles': {'calories': 138, 'protein': 4.5, 'carbs': 25, 'fat': 2.1},
      'oatmeal': {'calories': 68, 'protein': 2.4, 'carbs': 12, 'fat': 1.4},
      'orange zest': {'calories': 97, 'protein': 1.5, 'carbs': 25, 'fat': 0.3},
      'oxtail': {'calories': 202, 'protein': 30, 'carbs': 0, 'fat': 8.2},
      'paneer': {'calories': 265, 'protein': 20, 'carbs': 1.2, 'fat': 20},
      'parma ham': {'calories': 217, 'protein': 30, 'carbs': 0, 'fat': 9.8},
      'passata': {'calories': 29, 'protein': 1.6, 'carbs': 7, 'fat': 0.2},
      'peaches': {'calories': 39, 'protein': 0.9, 'carbs': 10, 'fat': 0.3},
      'peanut brittle': {'calories': 486, 'protein': 6.9, 'carbs': 70, 'fat': 19},
      'peanut cookies': {'calories': 488, 'protein': 9.2, 'carbs': 67, 'fat': 20},
      'peanuts': {'calories': 567, 'protein': 26, 'carbs': 16, 'fat': 49},
      'pears': {'calories': 57, 'protein': 0.4, 'carbs': 15, 'fat': 0.1},
      'pecan nuts': {'calories': 691, 'protein': 9.2, 'carbs': 14, 'fat': 72},
      'pecorino': {'calories': 387, 'protein': 32, 'carbs': 0.3, 'fat': 27},
      'penne rigate': {'calories': 131, 'protein': 5, 'carbs': 25, 'fat': 1.1},
      'pickle juice': {'calories': 1, 'protein': 0, 'carbs': 0.7, 'fat': 0},
      'pilchards': {'calories': 191, 'protein': 25, 'carbs': 0, 'fat': 9.3},
      'pink food colouring': {'calories': 0, 'protein': 0, 'carbs': 0, 'fat': 0},
      'pitted black olives': {'calories': 115, 'protein': 0.8, 'carbs': 6, 'fat': 11},
      'plain chocolate': {'calories': 546, 'protein': 4.9, 'carbs': 61, 'fat': 31},
      'pretzels': {'calories': 380, 'protein': 11, 'carbs': 80, 'fat': 2.8},
      'prunes': {'calories': 240, 'protein': 2.2, 'carbs': 64, 'fat': 0.4},
      'pumpkin': {'calories': 26, 'protein': 1, 'carbs': 6.5, 'fat': 0.1},
      'quinoa': {'calories': 120, 'protein': 4.4, 'carbs': 22, 'fat': 1.9},
      'ras el hanout': {'calories': 325, 'protein': 12, 'carbs': 47, 'fat': 12},
      'raspberry jam': {'calories': 246, 'protein': 0.3, 'carbs': 64, 'fat': 0.2},
      'redcurrants': {'calories': 56, 'protein': 1.4, 'carbs': 14, 'fat': 0.2},
      'refried beans': {'calories': 89, 'protein': 5.2, 'carbs': 15, 'fat': 1.2},
      'rhubarb': {'calories': 21, 'protein': 0.9, 'carbs': 4.5, 'fat': 0.2},
      'ricotta': {'calories': 174, 'protein': 11, 'carbs': 3, 'fat': 13},
      'rigatoni': {'calories': 131, 'protein': 5, 'carbs': 25, 'fat': 1.1},
      'roasted vegetables': {'calories': 65, 'protein': 2.2, 'carbs': 13, 'fat': 1.2},
      'rolled oats': {'calories': 389, 'protein': 17, 'carbs': 66, 'fat': 6.9},
      'sake': {'calories': 134, 'protein': 0.5, 'carbs': 5, 'fat': 0},
      'scallions': {'calories': 32, 'protein': 1.8, 'carbs': 7.3, 'fat': 0.2},
      'sesame seed': {'calories': 573, 'protein': 18, 'carbs': 23, 'fat': 50},
      'sherry': {'calories': 116, 'protein': 0.2, 'carbs': 1.4, 'fat': 0},
      'shortcrust pastry': {'calories': 449, 'protein': 6.1, 'carbs': 45, 'fat': 27},
      'shortening': {'calories': 900, 'protein': 0, 'carbs': 0, 'fat': 100},
      'smoked haddock': {'calories': 101, 'protein': 23, 'carbs': 0, 'fat': 0.9},
      'spaghetti': {'calories': 131, 'protein': 5, 'carbs': 25, 'fat': 1.1},
      'squash': {'calories': 40, 'protein': 1, 'carbs': 10, 'fat': 0.1},
      'stir-fry vegetables': {'calories': 35, 'protein': 2.5, 'carbs': 7, 'fat': 0.3},
      'strawberries': {'calories': 32, 'protein': 0.7, 'carbs': 8, 'fat': 0.3},
      'suet': {'calories': 854, 'protein': 1.5, 'carbs': 0, 'fat': 94},
      'sultanas': {'calories': 299, 'protein': 3.1, 'carbs': 79, 'fat': 0.5},
      'swede': {'calories': 37, 'protein': 1.1, 'carbs': 8.6, 'fat': 0.2},
      'tahini': {'calories': 595, 'protein': 17, 'carbs': 21, 'fat': 54},
      'tarragon leaves': {'calories': 295, 'protein': 22.8, 'carbs': 50, 'fat': 7.2},
      'thai fish sauce': {'calories': 35, 'protein': 5.8, 'carbs': 3.5, 'fat': 0},
      'thai green curry paste': {'calories': 85, 'protein': 2.1, 'carbs': 16, 'fat': 1.8},
      'thai red curry paste': {'calories': 89, 'protein': 2.4, 'carbs': 17, 'fat': 1.5},
      'toffee popcorn': {'calories': 429, 'protein': 2.8, 'carbs': 76, 'fat': 13},
      'tofu': {'calories': 76, 'protein': 8, 'carbs': 1.9, 'fat': 4.8},
      'toor dal': {'calories': 343, 'protein': 22, 'carbs': 62, 'fat': 1.5},
      'turkey mince': {'calories': 135, 'protein': 30, 'carbs': 0, 'fat': 0.7},
      'udon noodles': {'calories': 99, 'protein': 2.6, 'carbs': 21, 'fat': 0.5},
      'vinaigrette dressing': {'calories': 349, 'protein': 0.1, 'carbs': 35, 'fat': 24},
      'whole wheat': {'calories': 340, 'protein': 13, 'carbs': 72, 'fat': 2.5},
      'wonton skin': {'calories': 291, 'protein': 9.4, 'carbs': 59, 'fat': 1.1},
      
      // Final 27 missing ingredients for complete coverage
      'baking powder': {'calories': 53, 'protein': 0, 'carbs': 28, 'fat': 0},
      'barbeque sauce': {'calories': 172, 'protein': 0.6, 'carbs': 41, 'fat': 0.6},
      'brie': {'calories': 334, 'protein': 21, 'carbs': 0.5, 'fat': 28},
      'brussels sprouts': {'calories': 43, 'protein': 3.4, 'carbs': 9, 'fat': 0.3},
      'buckwheat': {'calories': 343, 'protein': 13, 'carbs': 72, 'fat': 3.4},
      'buns': {'calories': 300, 'protein': 8.5, 'carbs': 56, 'fat': 4.2},
      'cacao': {'calories': 228, 'protein': 19.6, 'carbs': 57.9, 'fat': 13.7},
      'cajun': {'calories': 289, 'protein': 12.8, 'carbs': 55, 'fat': 6.5},
      'caraway seed': {'calories': 333, 'protein': 19.8, 'carbs': 49.9, 'fat': 14.6},
      'challots': {'calories': 72, 'protein': 2.5, 'carbs': 17, 'fat': 0.1}, // Same as shallots
      'cornstarch': {'calories': 381, 'protein': 0.3, 'carbs': 91, 'fat': 0.1},
      'digestive biscuits': {'calories': 471, 'protein': 6.3, 'carbs': 66, 'fat': 20},
      'doner meat': {'calories': 280, 'protein': 26, 'carbs': 3, 'fat': 18},
      'fries': {'calories': 365, 'protein': 4, 'carbs': 63, 'fat': 17},
      'hotsauce': {'calories': 12, 'protein': 1.3, 'carbs': 0.8, 'fat': 0.8},
      'kielbasa': {'calories': 301, 'protein': 13, 'carbs': 4, 'fat': 26},
      'lasagne sheets': {'calories': 131, 'protein': 5, 'carbs': 25, 'fat': 1.1},
      'malt vinegar': {'calories': 18, 'protein': 0, 'carbs': 0.04, 'fat': 0},
      'marjoram': {'calories': 271, 'protein': 12.7, 'carbs': 60.6, 'fat': 7},
      'mayonnaise': {'calories': 680, 'protein': 1.1, 'carbs': 0.6, 'fat': 75},
      'puff pastry': {'calories': 558, 'protein': 7.9, 'carbs': 45, 'fat': 40},
      'rapeseed oil': {'calories': 884, 'protein': 0, 'carbs': 0, 'fat': 100},
      'salsa': {'calories': 36, 'protein': 1.6, 'carbs': 7, 'fat': 0.2},
      'scotch bonnet': {'calories': 40, 'protein': 1.9, 'carbs': 8.8, 'fat': 0.4},
      'tamarind paste': {'calories': 239, 'protein': 2.8, 'carbs': 63, 'fat': 0.6},
      'yeast': {'calories': 325, 'protein': 45, 'carbs': 41, 'fat': 7.6},
      'zucchini': {'calories': 17, 'protein': 1.2, 'carbs': 3.1, 'fat': 0.3},
    };
  }

  /// Get nutritional values for a specific ingredient
  /// Returns null if ingredient is not found in database
  static Map<String, double>? getIngredientNutrition(String ingredient) {
    final database = getDatabase();
    final normalizedIngredient = ingredient.toLowerCase().trim();
    return database[normalizedIngredient];
  }

  /// Check if an ingredient exists in the database
  static bool hasIngredient(String ingredient) {
    final database = getDatabase();
    final normalizedIngredient = ingredient.toLowerCase().trim();
    return database.containsKey(normalizedIngredient);
  }

  /// Get all ingredient names in the database
  static List<String> getAllIngredients() {
    return getDatabase().keys.toList()..sort();
  }

  /// Get database statistics
  static Map<String, int> getStats() {
    final database = getDatabase();
    return {
      'totalIngredients': database.length,
      'proteinsCount': database.values.where((nutrition) => nutrition['protein']! > 15).length,
      'vegetablesCount': database.keys.where((ingredient) => 
        ['tomato', 'onion', 'pepper', 'carrot', 'broccoli', 'spinach'].any((veg) => ingredient.contains(veg))
      ).length,
      'fruitsCount': database.keys.where((ingredient) => 
        ['apple', 'orange', 'banana', 'berry', 'grape'].any((fruit) => ingredient.contains(fruit))
      ).length,
    };
  }
}