// country_names.dart
final Map<String, Map<String, String>> countryNames = {
  'en': {
    'en': 'English',
    'es': 'Spanish', 
    'fr': 'French',
    'de': 'German',
    'it': 'Italian',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'ja': 'Japanese',
    'zh': 'Chinese (Traditional)',
    'hi': 'Hindi',
    'ko': 'Korean',
    // Country codes
    'us': 'United States',
    'uk': 'United Kingdom',
    'ca': 'Canada',
    'au': 'Australia',
    'br': 'Brazil',
    'mx': 'Mexico',
    'ar': 'Argentina',
    'jp': 'Japan',
    'kr': 'South Korea',
    'cn': 'China',
    'in': 'India',
    'za': 'South Africa',
    'eg': 'Egypt',
    'ng': 'Nigeria',
  },
  'fr': {
    'en': 'Anglais',
    'es': 'Espagnol',
    'fr': 'Français',
    'de': 'Allemand',
    'it': 'Italien',
    'pt': 'Portugais',
    'ru': 'Russe',
    'ja': 'Japonais',
    'zh': 'Chinois (Traditionnel)',
    'hi': 'Hindi',
    'ko': 'Coréen',
    // Country codes
    'us': 'États-Unis',
    'uk': 'Royaume-Uni',
    'ca': 'Canada',
    'au': 'Australie',
    'br': 'Brésil',
    'mx': 'Mexique',
    'ar': 'Argentine',
    'jp': 'Japon',
    'kr': 'Corée du Sud',
    'cn': 'Chine',
    'in': 'Inde',
    'za': 'Afrique du Sud',
    'eg': 'Égypte',
    'ng': 'Nigeria',
  },
  'de': {
    'en': 'Englisch',
    'es': 'Spanisch',
    'fr': 'Französisch',
    'de': 'Deutsch',
    'it': 'Italienisch',
    'pt': 'Portugiesisch',
    'ru': 'Russisch',
    'ja': 'Japanisch',
    'zh': 'Chinesisch (Traditionell)',
    'hi': 'Hindi',
    'ko': 'Koreanisch',
    // Country codes
    'us': 'Vereinigte Staaten',
    'uk': 'Vereinigtes Königreich',
    'ca': 'Kanada',
    'au': 'Australien',
    'br': 'Brasilien',
    'mx': 'Mexiko',
    'ar': 'Argentinien',
    'jp': 'Japan',
    'kr': 'Südkorea',
    'cn': 'China',
    'in': 'Indien',
    'za': 'Südafrika',
    'eg': 'Ägypten',
    'ng': 'Nigeria',
  },
  'es': {
    'en': 'Inglés',
    'es': 'Español',
    'fr': 'Francés',
    'de': 'Alemán',
    'it': 'Italiano',
    'pt': 'Portugués',
    'ru': 'Ruso',
    'ja': 'Japonés',
    'zh': 'Chino (Tradicional)',
    'hi': 'Hindi',
    'ko': 'Coreano',
    // Country codes
    'us': 'Estados Unidos',
    'uk': 'Reino Unido',
    'ca': 'Canadá',
    'au': 'Australia',
    'br': 'Brasil',
    'mx': 'México',
    'ar': 'Argentina',
    'jp': 'Japón',
    'kr': 'Corea del Sur',
    'cn': 'China',
    'in': 'India',
    'za': 'Sudáfrica',
    'eg': 'Egipto',
    'ng': 'Nigeria',
  },
  'pt': {
    'en': 'Inglês',
    'es': 'Espanhol',
    'fr': 'Francês',
    'de': 'Alemão',
    'it': 'Italiano',
    'pt': 'Português',
    'ru': 'Russo',
    'ja': 'Japonês',
    'zh': 'Chinês (Tradicional)',
    'hi': 'Hindi',
    'ko': 'Coreano',
    // Country codes
    'us': 'Estados Unidos',
    'uk': 'Reino Unido',
    'ca': 'Canadá',
    'au': 'Austrália',
    'br': 'Brasil',
    'mx': 'México',
    'ar': 'Argentina',
    'jp': 'Japão',
    'kr': 'Coreia do Sul',
    'cn': 'China',
    'in': 'Índia',
    'za': 'África do Sul',
    'eg': 'Egito',
    'ng': 'Nigéria',
  },
  'it': {
    'en': 'Inglese',
    'es': 'Spagnolo',
    'fr': 'Francese',
    'de': 'Tedesco',
    'it': 'Italiano',
    'pt': 'Portoghese',
    'ru': 'Russo',
    'ja': 'Giapponese',
    'zh': 'Cinese (Tradizionale)',
    'hi': 'Hindi',
    'ko': 'Coreano',
    // Country codes
    'us': 'Stati Uniti',
    'uk': 'Regno Unito',
    'ca': 'Canada',
    'au': 'Australia',
    'br': 'Brasile',
    'mx': 'Messico',
    'ar': 'Argentina',
    'jp': 'Giappone',
    'kr': 'Corea del Sud',
    'cn': 'Cina',
    'in': 'India',
    'za': 'Sudafrica',
    'eg': 'Egitto',
    'ng': 'Nigeria',
  },
  'ru': {
    'en': 'Английский',
    'es': 'Испанский',
    'fr': 'Французский',
    'de': 'Немецкий',
    'it': 'Итальянский',
    'pt': 'Португальский',
    'ru': 'Русский',
    'ja': 'Японский',
    'zh': 'Китайский (традиционный)',
    'hi': 'Хинди',
    'ko': 'Корейский',
    // Country codes
    'us': 'США',
    'uk': 'Великобритания',
    'ca': 'Канада',
    'au': 'Австралия',
    'br': 'Бразилия',
    'russia': 'Россия',
    'cn': 'Китай',
    'jp': 'Япония',
    'in': 'Индия',
  },
  'ja': {
    'en': '英語',
    'es': 'スペイン語',
    'fr': 'フランス語',
    'de': 'ドイツ語',
    'it': 'イタリア語',
    'pt': 'ポルトガル語',
    'ru': 'ロシア語',
    'ja': '日本語',
    'zh': '中国語（繁体字）',
    'hi': 'ヒンディー語',
    'ko': '韓国語',
    // Country codes
    'us': 'アメリカ',
    'uk': 'イギリス',
    'ca': 'カナダ',
    'au': 'オーストラリア',
    'br': 'ブラジル',
    'jp': '日本',
    'kr': '韓国',
    'cn': '中国',
    'in': 'インド',
  },
  'zh': {
    'en': '英語',
    'es': '西班牙語',
    'fr': '法語',
    'de': '德語',
    'it': '意大利語',
    'pt': '葡萄牙語',
    'ru': '俄語',
    'ja': '日本語',
    'zh': '中文 (繁體)',
    'hi': '印地語',
    'ko': '韓語',
    // Country codes
    'us': '美國',
    'uk': '英國',
    'ca': '加拿大',
    'au': '澳大利亞',
    'cn': '中國',
    'jp': '日本',
    'kr': '韓國',
    'in': '印度',
  },
  'hi': {
    'en': 'अंग्रेजी',
    'es': 'स्पेनिश',
    'fr': 'फ्रेंच',
    'de': 'जर्मन',
    'it': 'इतालवी',
    'pt': 'पुर्तगाली',
    'ru': 'रूसी',
    'ja': 'जापानी',
    'zh': 'चीनी (पारंपरिक)',
    'hi': 'हिन्दी',
    'ko': 'कोरियाई',
    // Country codes
    'us': 'संयुक्त राज्य',
    'uk': 'यूनाइटेड किंगडम',
    'ca': 'कनाडा',
    'au': 'ऑस्ट्रेलिया',
    'cn': 'चीन',
    'jp': 'जापान',
    'in': 'भारत',
    'kr': 'दक्षिण कोरिया',
  },
  'ko': {
    'en': '영어',
    'es': '스페인어',
    'fr': '프랑스어',
    'de': '독일어',
    'it': '이탈리아어',
    'pt': '포르투갈어',
    'ru': '러시아어',
    'ja': '일본어',
    'zh': '중국어 (번체)',
    'hi': '힌디어',
    'ko': '한국어',
    // Country codes
    'us': '미국',
    'uk': '영국',
    'ca': '캐나다',
    'au': '호주',
    'cn': '중국',
    'jp': '일본',
    'kr': '한국',
    'in': '인도',
  },
};
