// country_names.dart
final Map<String, Map<String, String>> countryNames = {
  'en': {
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'de': 'German',
    'it': 'Italian',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'ja': 'Japanese',
    'zh': 'Chinese (Traditional)',
    'hi': 'Hindi',
    'ko': 'Korean',
  },
  'fr': {
    'en': 'Anglais',
    'es': 'Espagnol',
    'fr': 'Français',
    'de': 'Allemand',
    'it': 'Italien',
    'pt': 'Portugais',
    'ru': 'Russe',
    'ja': 'Japonais',
    'zh': 'Chinois (Traditionnel)',
    'hi': 'Hindi',
    'ko': 'Coréen',
  },
  'de': {
    'en': 'Englisch',
    'es': 'Spanisch',
    'fr': 'Französisch',
    'de': 'Deutsch',
    'it': 'Italienisch',
    'pt': 'Portugiesisch',
    'ru': 'Russisch',
    'ja': 'Japanisch',
    'zh': 'Chinesisch (Traditionell)',
    'hi': 'Hindi',
    'ko': 'Koreanisch',
  },
  'es': {
    'en': 'Inglés',
    'es': 'Español',
    'fr': 'Francés',
    'de': 'Alemán',
    'it': 'Italiano',
    'pt': 'Portugués',
    'ru': 'Ruso',
    'ja': 'Japonés',
    'zh': 'Chino (Tradicional)',
    'hi': 'Hindi',
    'ko': 'Coreano',
  },
  'pt': {
    'en': 'Inglês',
    'es': 'Espanhol',
    'fr': 'Francês',
    'de': 'Alemão',
    'it': 'Italiano',
    'pt': 'Português',
    'ru': 'Russo',
    'ja': 'Japonês',
    'zh': 'Chinês (Tradicional)',
    'hi': 'Hindi',
    'ko': 'Coreano',
  },
  'it': {
    'en': 'Inglese',
    'es': 'Spagnolo',
    'fr': 'Francese',
    'de': 'Tedesco',
    'it': 'Italiano',
    'pt': 'Portoghese',
    'ru': 'Russo',
    'ja': 'Giapponese',
    'zh': 'Cinese (Tradizionale)',
    'hi': 'Hindi',
    'ko': 'Coreano',
  },
  'ru': {
    'en': 'Английский',
    'es': 'Испанский',
    'fr': 'Французский',
    'de': 'Немецкий',
    'it': 'Итальянский',
    'pt': 'Португальский',
    'ru': 'Русский',
    'ja': 'Японский',
    'zh': 'Китайский (традиционный)',
    'hi': 'Хинди',
    'ko': 'Корейский',
  },
  'ja': {
    'en': '英語',
    'es': 'スペイン語',
    'fr': 'フランス語',
    'de': 'ドイツ語',
    'it': 'イタリア語',
    'pt': 'ポルトガル語',
    'ru': 'ロシア語',
    'ja': '日本語',
    'zh': '中国語（繁体字）',
    'hi': 'ヒンディー語',
    'ko': '韓国語',
  },
  'zh': {
    'en': '英語',
    'es': '西班牙語',
    'fr': '法語',
    'de': '德語',
    'it': '意大利語',
    'pt': '葡萄牙語',
    'ru': '俄語',
    'ja': '日本語',
    'zh': '中文 (繁體)',
    'hi': '印地語',
    'ko': '韓語',
  },
  'hi': {
    'en': 'अंग्रेजी',
    'es': 'स्पेनिश',
    'fr': 'फ्रेंच',
    'de': 'जर्मन',
    'it': 'इतालवी',
    'pt': 'पुर्तगाली',
    'ru': 'रूसी',
    'ja': 'जापानी',
    'zh': 'चीनी (पारंपरिक)',
    'hi': 'हिन्दी',
    'ko': 'कोरियाई',
  },
  'ko': {
    'en': '영어',
    'es': '스페인어',
    'fr': '프랑스어',
    'de': '독일어',
    'it': '이탈리아어',
    'pt': '포르투갈어',
    'ru': '러시아어',
    'ja': '일본어',
    'zh': '중국어 (번체)',
    'hi': '힌디어',
    'ko': '한국어',
  },
};
