// country_names.dart
final Map<String, Map<String, String>> countryNames = {
  'en': {
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'de': 'German',
    'it': 'Italian',
    'pt': 'Portuguese',
    'ja': 'Japanese',
    'ko': 'Korean',
    'zh': 'Chinese',
  },
  'fr': {
    'en': 'Anglais',
    'es': 'Espagnol',
    'fr': 'Français',
    'de': 'Allemand',
    'it': 'Italien',
    'pt': 'Portugais',
    'ja': 'Japonais',
    'ko': 'Coréen',
    'zh': 'Chinois',
  },
  'de': {
    'en': 'Englisch',
    'es': 'Spanisch',
    'fr': 'Französisch',
    'de': 'Deutsch',
    'it': 'Italienisch',
    'pt': 'Portugiesisch',
    'ja': 'Japanisch',
    'ko': 'Koreanisch',
    'zh': 'Chinesisch',
  },
  'es': {
    'en': 'Inglés',
    'es': 'Español',
    'fr': 'Francés',
    'de': 'Alemán',
    'it': 'Italiano',
    'pt': 'Portugués',
    'ja': 'Japonés',
    'ko': 'Coreano',
    'zh': 'Chino',
  },
  'pt': {
    'en': 'Inglês',
    'es': 'Espanhol',
    'fr': 'Francês',
    'de': 'Alemão',
    'it': 'Italiano',
    'pt': 'Português',
    'ja': 'Japonês',
    'ko': 'Coreano',
    'zh': 'Chinês',
  },
  'it': {
    'en': 'Inglese',
    'es': 'Spagnolo',
    'fr': 'Francese',
    'de': 'Tedesco',
    'it': 'Italiano',
    'pt': 'Portoghese',
    'ja': 'Giapponese',
    'ko': 'Coreano',
    'zh': 'Cinese',
  },
  'ja': {
    'en': '英語',
    'es': 'スペイン語',
    'fr': 'フランス語',
    'de': 'ドイツ語',
    'it': 'イタリア語',
    'pt': 'ポルトガル語',
    'ja': '日本語',
    'ko': '韓国語',
    'zh': '中国語',
  },
  'ko': {
    'en': '영어',
    'es': '스페인어',
    'fr': '프랑스어',
    'de': '독일어',
    'it': '이탈리아어',
    'pt': '포르투갈어',
    'ja': '일본어',
    'ko': '한국어',
    'zh': '중국어',
  },
  'zh': {
    'en': '英语',
    'es': '西班牙语',
    'fr': '法语',
    'de': '德语',
    'it': '意大利语',
    'pt': '葡萄牙语',
    'ja': '日语',
    'ko': '韩语',
    'zh': '中文',
  },
};
