// lib/screens/search/workout_detail/workout_data.dart
import 'models/workout_item.dart';
import 'models/workout_step.dart';

List<WorkoutStep> createWorkoutSteps(List<String> stepTitles) {
  return stepTitles
      .map((title) => WorkoutStep(
            title: title,
            duration: '1 min',
            description: 'Perform $title with proper form',
            instructions: [
              'Start in proper position',
              'Maintain form throughout',
              'Control your breathing',
              'Complete the movement'
            ],
          ))
      .toList();
}

Map<String, List<WorkoutItem>> categoryWorkouts = {
  'workout_strength': [
    WorkoutItem(
      title: 'strength_workout_1',
      image: 'assets/images/search/strength_training/strength-1.jpg',
      duration: '45 min',
      difficulty: 'Medium',
      description:
          'Complete upper body strength workout focusing on building muscle and strength',
      rating: 4.5,
      caloriesBurn: '350',
      steps: createWorkoutSteps([
        'warmup_strength',
        'chest_press',
        'shoulder_press',
        'back_rows',
        'bicep_curls',
        'tricep_extensions',
        'cooldown_strength',
      ]),
    ),
    WorkoutItem(
      title: 'strength_workout_2',
      image: 'assets/images/search/strength_training/strength-2.jpg',
      duration: '50 min',
      difficulty: 'Hard',
      description:
          'Lower body strength training session targeting all major muscle groups',
      rating: 4.7,
      caloriesBurn: '400',
      steps: createWorkoutSteps([
        'warmup_strength',
        'deadlifts',
        'squats',
        'lunges',
        'leg_press',
        'calf_raises',
        'cooldown_strength',
      ]),
    ),
    WorkoutItem(
      title: 'strength_workout_3',
      image: 'assets/images/search/strength_training/strength.jpg',
      duration: '40 min',
      difficulty: 'Easy',
      description:
          'Beginner-friendly full body strength workout with basic movements',
      rating: 4.3,
      caloriesBurn: '300',
      steps: createWorkoutSteps([
        'warmup_strength',
        'pushups',
        'dumbbell_rows',
        'lateral_raises',
        'tricep_dips',
        'face_pulls',
        'cooldown_strength',
      ]),
    ),
  ],
  'workout_abs': [
    WorkoutItem(
      title: 'abs_workout_1',
      image: 'assets/images/search/abs_cardio/abs-1.jpg',
      duration: '30 min',
      difficulty: 'Medium',
      description:
          'Core-focused workout to strengthen your abs and improve stability',
      rating: 4.6,
      caloriesBurn: '250',
      steps: createWorkoutSteps([
        'warmup_core',
        'crunches',
        'plank',
        'bicycle_crunches',
        'leg_raises',
        'russian_twists',
        'cooldown_core',
      ]),
    ),
    WorkoutItem(
      title: 'abs_workout_2',
      image: 'assets/images/search/abs_cardio/abs-2.jpg',
      duration: '25 min',
      difficulty: 'Hard',
      description:
          'Advanced core workout with challenging movements for experienced athletes',
      rating: 4.8,
      caloriesBurn: '300',
      steps: createWorkoutSteps([
        'warmup_core',
        'hollow_body_holds',
        'dragon_flags',
        'hanging_leg_raises',
        'ab_wheel_rollouts',
        'windshield_wipers',
        'cooldown_core',
      ]),
    ),
    WorkoutItem(
      title: 'abs_cardio_combo',
      image: 'assets/images/search/abs_cardio/cardio.jpg',
      duration: '35 min',
      difficulty: 'Medium',
      description: 'Combined cardio and core workout for maximum fat burning',
      rating: 4.7,
      caloriesBurn: '400',
      steps: createWorkoutSteps([
        'warmup_cardio',
        'mountain_climbers',
        'burpees',
        'plank_to_downward_dog',
        'jumping_jacks',
        'high_knees',
        'cooldown_cardio',
      ]),
    ),
  ],
  'workout_outdoor': [
    WorkoutItem(
      title: 'outdoor_run_1',
      image: 'assets/images/search/outdoor_activities/running.jpg',
      duration: '40 min',
      difficulty: 'Medium',
      description:
          'Progressive outdoor running session with varied intensities',
      rating: 4.5,
      caloriesBurn: '450',
      steps: createWorkoutSteps([
        'warmup_running',
        'light_jog',
        'speed_intervals',
        'hill_sprints',
        'steady_pace',
        'cool_down_jog',
        'stretching',
      ]),
    ),
    WorkoutItem(
      title: 'outdoor_hiit',
      image: 'assets/images/search/outdoor_activities/running-1.jpg',
      duration: '30 min',
      difficulty: 'Hard',
      description: 'High-intensity interval training in the outdoors',
      rating: 4.9,
      caloriesBurn: '500',
      steps: createWorkoutSteps([
        'warmup_dynamic',
        'sprint_intervals',
        'bodyweight_exercises',
        'agility_drills',
        'power_moves',
        'cooldown_stretches',
      ]),
    ),
    WorkoutItem(
      title: 'outdoor_endurance',
      image: 'assets/images/search/outdoor_activities/running-2.jpg',
      duration: '60 min',
      difficulty: 'Medium',
      description: 'Long-distance endurance training to build stamina',
      rating: 4.6,
      caloriesBurn: '600',
      steps: createWorkoutSteps([
        'warmup_mobility',
        'long_distance_run',
        'tempo_running',
        'recovery_periods',
        'cooldown_routine',
      ]),
    ),
  ],
  'workout_yoga': [
    WorkoutItem(
      title: 'yoga_flow_1',
      image: 'assets/images/search/yoga_sessions/yoga.jpg',
      duration: '45 min',
      difficulty: 'Easy',
      description: 'Gentle flow yoga session perfect for beginners',
      rating: 4.4,
      caloriesBurn: '200',
      steps: createWorkoutSteps([
        'breathing_exercises',
        'sun_salutations',
        'standing_poses',
        'balance_poses',
        'floor_poses',
        'final_relaxation',
      ]),
    ),
    WorkoutItem(
      title: 'power_yoga',
      image: 'assets/images/search/yoga_sessions/yoga-1.jpg',
      duration: '50 min',
      difficulty: 'Medium',
      description: 'Dynamic power yoga session for strength and flexibility',
      rating: 4.7,
      caloriesBurn: '300',
      steps: createWorkoutSteps([
        'warmup_flow',
        'power_sequences',
        'core_work',
        'inversions',
        'backbends',
        'cool_down_flow',
      ]),
    ),
    WorkoutItem(
      title: 'gentle_yoga',
      image: 'assets/images/search/yoga_sessions/yoga-2.jpg',
      duration: '40 min',
      difficulty: 'Easy',
      description:
          'Relaxing yoga session focusing on flexibility and mindfulness',
      rating: 4.5,
      caloriesBurn: '150',
      steps: createWorkoutSteps([
        'gentle_breathing',
        'easy_stretches',
        'restorative_poses',
        'meditation',
        'relaxation',
      ]),
    ),
  ],
  'workout_calisthenics': [
    WorkoutItem(
      title: 'calisthenics_basics',
      image: 'assets/images/search/calisthenics/calisthenics.jpg',
      duration: '45 min',
      difficulty: 'Medium',
      description: 'Foundation calisthenics workout for bodyweight mastery',
      rating: 4.6,
      caloriesBurn: '350',
      steps: createWorkoutSteps([
        'warmup_mobility',
        'pushup_variations',
        'pullup_progression',
        'squat_practice',
        'handstand_prep',
        'cooldown_routine',
      ]),
    ),
    WorkoutItem(
      title: 'advanced_calisthenics',
      image: 'assets/images/search/calisthenics/calisthenics-1.jpg',
      duration: '55 min',
      difficulty: 'Hard',
      description: 'Advanced calisthenics skills and strength training',
      rating: 4.9,
      caloriesBurn: '450',
      steps: createWorkoutSteps([
        'skill_warmup',
        'muscle_ups',
        'front_lever_work',
        'planche_training',
        'handstand_pushups',
        'flexibility_work',
      ]),
    ),
    WorkoutItem(
      title: 'calisthenics_skills',
      image: 'assets/images/search/calisthenics/calisthenics-2.jpg',
      duration: '50 min',
      difficulty: 'Medium',
      description: 'Skill-based calisthenics session for movement mastery',
      rating: 4.7,
      caloriesBurn: '400',
      steps: createWorkoutSteps([
        'mobility_prep',
        'basic_skills',
        'strength_elements',
        'static_holds',
        'flow_practice',
        'cooldown_mobility',
      ]),
    ),
  ],
  'workout_meditation': [
    WorkoutItem(
      title: 'mindful_meditation',
      image: 'assets/images/search/meditation/meditation.jpg',
      duration: '20 min',
      difficulty: 'Easy',
      description: 'Guided mindfulness meditation for mental clarity',
      rating: 4.4,
      caloriesBurn: '50',
      steps: createWorkoutSteps([
        'breathing_awareness',
        'body_scan',
        'thought_observation',
        'mindful_sitting',
        'gentle_closure',
      ]),
    ),
    WorkoutItem(
      title: 'stress_relief',
      image: 'assets/images/search/meditation/meditation-1.jpg',
      duration: '25 min',
      difficulty: 'Easy',
      description: 'Meditation session focused on reducing stress and anxiety',
      rating: 4.6,
      caloriesBurn: '50',
      steps: createWorkoutSteps([
        'relaxation_breathing',
        'stress_release',
        'mental_clarity',
        'peace_practice',
        'gratitude_meditation',
      ]),
    ),
    WorkoutItem(
      title: 'energy_meditation',
      image: 'assets/images/search/meditation/meditation-2.jpg',
      duration: '15 min',
      difficulty: 'Easy',
      description: 'Energizing meditation to boost focus and vitality',
      rating: 4.5,
      caloriesBurn: '50',
      steps: createWorkoutSteps([
        'energizing_breath',
        'mindful_movement',
        'focus_practice',
        'visualization',
        'awakening_meditation',
      ]),
    ),
  ],
};
